; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26730.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\alexa\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
